version: '3'
services:
    front:
        container_name: front
        ports:
            - 8000:80
        build: 
            context: .
            dockerfile: front.Dockerfile
    back: 
        container_name: back
        ports: 
            - 8001:8000
        build: 
            context: .
            dockerfile: back.Dockerfile
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/proxy.nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - front
            - back
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9000:9000'
        depends_on: 
            - front

volumes:
    prometheus_data: {}
