version: '3'
services:
    front:
        container_name: front
        ports:
            - 8000:80
        build: 
            context: .
            dockerfile: front.Dockerfile
    back: 
        container_name: back
        ports: 
            - 8001:8000
        build: 
            context: .
            dockerfile: back.Dockerfile
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/proxy.nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - front
            - back
